Update script.js
elviraff/ice_wine_basic_js pull request #3
Opened 2021-08-24 22:06 UTC by elviraff

2021-08-30 22:24 UTC, Om1X requested changes

2021-08-30 22:24 UTC, Om1X commented on script.js
> +var marr = [];
этот массив тут лишний

2021-08-30 22:24 UTC, Om1X commented on script.js
> +var sum = 0;
sum нужно перенести внутрь функции

2021-09-05 15:07 UTC, closed without merging

2021-09-05 15:07 UTC, elviraff commented
see next